language: c

compiler:
    - clang
    - gcc

script: make && make test

addons:
    apt:
        packages:
            - cmake
            - libyaml-dev
            - libjansson-dev
            - libflac-dev
            - libogg-dev
            - libvorbis-dev
            - libtagc0-dev

sudo: required
dist: trusty
